### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by shtirlits-bsa20** [shtirlits-bsa20/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by LH346** [comment]
— Founder of National Socialism, Reich Chancellor, dictator of the Third Reich, Fuhrer of the NSDAP and Germany. He is the man who unleashed the Second World War.

**Comment by shtirlits-bsa20** [comment]
Thank you sir!
