### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by shtirlits-bsa20** [shtirlits-bsa20/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by LH346** [comment]
1941

In 1941, Adolf Hitler, Heinrich Himmler, Reinhard Heydrich and other leading German authorities reach the decision to physically annihilate the Jews of Europe.

Fall 1939 or early January 1940

Adolf Hitler signs a secret authorization for a “euthanasia’” program, the systematic killing of patients with mental and physical disabilities who are living in institutional settings in Germany and German-annexed territories. It is the only instance in which Hitler signs an authorization for a program of systematic mass murder.

September 1, 1939

Nazi Germany invades Poland, initiating World War II.

August 23, 1939

German and Soviet foreign ministers Ribbentrop and Molotov, respectively, sign a German-Soviet Pact. The main tenet of this agreement is a ten-year non-aggression pact in which each signatory promises not to attack the other.

January 23, 1939

In a speech to the German parliament in January 1939, Hitler states that another world war will result in the elimination of Jews from Europe.

1938

Hitler meets with the leaders of Britain, France, and Italy at a conference in Munich, Germany, on September 29–30, 1938, in which they agree to the German annexation of the Sudetenland in exchange for a pledge of peace from Germany. Six months later, Hitler moves against the Czechoslovak state.

March 23, 1933

Following the burning of the German parliament building, the Reichstag, by unknown arsonists, the German parliament passes the Law for Rectification of the Distress of Nation and Reich, commonly known as the Enabling Act (Ermächtigungsgesetz). This law allows Hitler, as Chancellor, to initiate and sign legislation into law without obtaining parliamentary consent. The act effectively establishes a dictatorship, under Hitler, in Germany.

January 1933

The Nazi Party comes to power with the appointment of Adolf Hitler as Chancellor.

**Comment by shtirlits-bsa20** [comment]
Thank you sir!
